name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'work/hello/pom.xml' # optional
      - name: Build with Maven
        working-directory: work/hello
        run: mvn -B package
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Run Hello
        working-directory: work/hello
        run: |
          ls 
          ls ./target
          pwd
          java -jar target/hello-1.0-SNAPSHOT.jar
      - run: echo "ğŸ This job's status is ${{ job.status }}."


